### ISSUE TITLE
Research kubernetes-provider-alpha deployment

### ISSUE THREAD

**Issue by wisack** [smaddis/common-issues#11]
Research if kubernetes provider alpha is suitable for us
https://www.hashicorp.com/blog/deploy-any-resource-with-the-new-kubernetes-provider-for-hashicorp-terraform
Linked #9

**Comment by msrn** [comment]
> Please regard this project as experimental. It still requires extensive testing and polishing to mature into production-ready quality. At this time, we are not planning to create a migration path for resources created with the kubernetes-alpha provider when the manifest resource is merged into the official kubernetes provider. **For this reason, please do not rely on this provider for production use while we strive towards project maturity**

For this reason I don't think we should use this.

How about just using the [current stable provider] (https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/guides/getting-started#creating-your-first-kubernetes-resources) ?

**Comment by hjhsalo** [comment]
We will use the stable provider since alpha provider might change in the future.
