### ISSUE TITLE
Document how to deploy Hono without optional Jaeger support

### ISSUE THREAD

**Issue by JouHouFin** [smaddis/common-issues#18]
Eclipse Hono has built-in support for Jaeger monitoring: https://www.eclipse.org/hono/docs/admin-guide/monitoring-tracing-config/#configuring-a-tracer

Investigate if it is possible (and useful) to enable the Jaeger support only if needed.

**Comment by ghost** [comment]
Hono built-in Jaeger support is disabled by default.
Commit smaddis/smad-deploy-azure/11e73a2 moves away from built-in jaeger support
