### ISSUE TITLE
Investigate need for Grafana in Prometheus deployment

### ISSUE THREAD

**Issue by JouHouFin** [smaddis/common-issues#20]
Prometheus has support for multiple timeseries-databases. It also has built-in support for Grafana.
Investigate if Grafana is the optimal solution for viewing the Prometheus statistics, or should we use some other service, or not use a service at all.

**Comment by hjhsalo** [comment]
As discussed Grafana is a central piece for visualizing Prometheus data. Grafana will be used in final "product"
