### ISSUE TITLE
Helm charts for MongoDB and PostgreSQL

### ISSUE THREAD

**Issue by JouHouFin** [smaddis/common-issues#29]
We may need MongoDB for Hono device registry and PostgreSQL for metrics/tracing data. The data also needs to be persistent.

Bitnami has Helm charts for installing both databases:
https://github.com/bitnami/azure-marketplace-charts/tree/master/bitnami/mongodb
https://github.com/bitnami/azure-marketplace-charts/tree/master/bitnami/postgresql

Investigate if these are suitable and configurable for our use-cases.

@Nindemic heads up!

**Comment by hjhsalo** [comment]
TimescaleDB has been selected for Prometheus.
See https://github.com/smaddis/smad-deploy-azure/issues/38 for details on MongoDB
