### ISSUE TITLE
Investigate: Separate static  container registry

### ISSUE THREAD

**Issue by msrn** [smaddis/common-issues#37]
**Let's fetch needed images and store them as simple tar packages in some external storage service.**

Currently container registry is created under the kubernetes cluster.

Problems with this:
- Pull and push images to ACR everytime new cluster is deployed

Proposed alternative:
Create separate static (private?) container registry that hosts all the images we need. 
With this we can pull images from our container registry without doing #36.

Possible container registries:
- Github Container Registry
- Separate Azure Container Registry
- Docker Hub

Problems:
- Pricing. Currently during beta Github Container Registry is free
- Hono images are well over 6GB's (?) in size

Info:

[Container registry with Github](https://roadtoalm.com/2020/09/22/using-the-github-container-registry-with-azure-kubernetes-service-aks/)

**Comment by msrn** [comment]
Currently testing using this [Github organisation as a registry ](https://github.com/orgs/smaddis/packages)and ACR.

**Comment by hjhsalo** [comment]
Implementing a container registry would be nice but it seems that we just don't have time to do it now.

Let's fetch needed images and store them as simple tar packages in some external storage service.

**Comment by msrn** [comment]
Current size 3,28GB. Uploaded to GDrive
