### ISSUE TITLE
Check if Terraform+helm is good idea for Hono deployment

### ISSUE THREAD

**Issue by laavamara** [smaddis/common-issues#9]
Find out if it's advicable to deploy Hono via Terraform+helm or some other way 
Link to actual deployment script issue #7

**Comment by msrn** [comment]
Additional info:
[Using Hono helm chart](https://github.com/eclipse/packages/blob/master/charts/hono/README.md)
[Terrafrom and helm example](https://registry.terraform.io/providers/hashicorp/helm/latest/docs)

For consideration:
https://docs.microsoft.com/en-us/azure/aks/kubernetes-walkthrough
https://www.eclipse.org/hono/docs/dev/deployment/helm-based-deployment/
https://docs.microsoft.com/en-us/azure/aks/kubernetes-helm

**Comment by msrn** [comment]
Work being done here https://github.com/smaddis/smad-hono/commit/eed94da8f218a9ee8c3c520a43545273357235a0

Ping @laavamara

**Comment by msrn** [comment]
With the offical Hono chart we can deploy most of our stack, and we can configure [values.yaml](https://github.com/eclipse/packages/blob/master/charts/hono/values.yaml) with our Terraform script.

We can also instruct Helm to use [custom container registry](https://github.com/eclipse/packages/tree/master/charts/hono#using-specific-container-images)

**Comment by msrn** [comment]
Should this be closed with https://github.com/smaddis/smad-deploy-azure/pull/31 ? We've pretty much decided to go forth with Helm based deployment and the current script is fully funtional in that regard.

**Comment by msrn** [comment]
Closed during 2021-03-08 meeting
